# Generated by Django 4.2.7 on 2024-02-19 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.booking')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service.service')),
            ],
        ),
    ]
