# Generated by Django 5.0.1 on 2024-02-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Reservado', max_length=30),
        ),
    ]
