# Generated by Django 5.0.2 on 2024-02-27 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('cabin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_cabin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.booking')),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cabin.cabin')),
            ],
        ),
    ]
