# Generated by Django 5.0.2 on 2024-02-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('document', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('cellphone', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
