# Generated by Django 5.0.1 on 2024-03-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_type', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabin_type',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
