# Generated by Django 5.0.1 on 2024-03-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_type', '0002_cabin_type_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabin_type',
            name='image',
            field=models.ImageField(null=True, upload_to='static/cabin_type_images'),
        ),
    ]
